"""Synthetic ChArUco round-trip tests.

Render the board to a virtual camera, run detect+pose, recover the known pose.
No hardware required.
"""
import cv2
import numpy as np

from cam_calib.core.charuco import (
    DEFAULT_BOARD,
    detect_board,
    estimate_board_pose,
)


def _render_board(board, board_spec, K, dist, T_board_cam, image_size=(1280, 720)):
    """Project the board's marker corners onto a synthetic camera image."""
    W, H = image_size

    sq_px = 80
    nx, ny = board_spec.size
    board_img = board.generateImage(
        outSize=(nx * sq_px, ny * sq_px), marginSize=20, borderBits=1
    )
    board_img_rgb = cv2.cvtColor(board_img, cv2.COLOR_GRAY2BGR)

    # Board frame: corners at z=0, x in [0, nx*square_length], y in [0, ny*square_length]
    bw, bh = board_img_rgb.shape[1], board_img_rgb.shape[0]
    board_world_corners = np.array(
        [
            [0.0, 0.0, 0.0],
            [nx * board_spec.square_length, 0.0, 0.0],
            [nx * board_spec.square_length, ny * board_spec.square_length, 0.0],
            [0.0, ny * board_spec.square_length, 0.0],
        ],
        dtype=np.float32,
    )
    src_corners = np.array(
        [[0, 0], [bw - 1, 0], [bw - 1, bh - 1], [0, bh - 1]], dtype=np.float32
    )
    # Project board world corners through T_board_cam into image plane.
    rvec, _ = cv2.Rodrigues(T_board_cam[:3, :3])
    tvec = T_board_cam[:3, 3]
    img_pts, _ = cv2.projectPoints(board_world_corners, rvec, tvec, K, dist)
    img_pts = img_pts.reshape(-1, 2).astype(np.float32)

    H_mat = cv2.getPerspectiveTransform(src_corners, img_pts)
    warped = cv2.warpPerspective(board_img_rgb, H_mat, (W, H), borderValue=(255, 255, 255))
    # Composite onto white background — the warp already leaves white outside.
    return warped


def test_charuco_round_trip():
    K = np.array(
        [[900.0, 0.0, 640.0], [0.0, 900.0, 360.0], [0.0, 0.0, 1.0]],
        dtype=np.float64,
    )
    dist = np.zeros(5, dtype=np.float64)

    # True board pose: ~0.5m in front of camera, slight tilt.
    rvec_true = np.array([0.1, 0.05, 0.0])
    tvec_true = np.array([-0.1, -0.05, 0.5])
    R, _ = cv2.Rodrigues(rvec_true)
    T_board_cam_true = np.eye(4)
    T_board_cam_true[:3, :3] = R
    T_board_cam_true[:3, 3] = tvec_true

    board, _ = DEFAULT_BOARD.opencv_board()
    img = _render_board(board, DEFAULT_BOARD, K, dist, T_board_cam_true)

    detection = detect_board(img, K, dist, DEFAULT_BOARD)
    assert detection is not None, "synthetic render should be detectable"
    assert len(detection.corners) >= 6

    pose = estimate_board_pose(detection, K, dist, DEFAULT_BOARD)
    assert pose is not None

    # The synthetic image is generated by a planar warp, not a true 3D render,
    # so we only check the pose is in the right ballpark — the goal here is to
    # exercise the detect → estimate pipeline end-to-end.
    np.testing.assert_allclose(pose.tvec.flatten(), tvec_true, atol=0.1)
    R_est, _ = cv2.Rodrigues(pose.rvec)
    cos_angle = np.clip((np.trace(R_est.T @ R) - 1) / 2, -1.0, 1.0)
    angle_err = np.degrees(np.arccos(cos_angle))
    assert angle_err < 10.0
    assert pose.reprojection_error < 5.0


def test_detect_returns_none_on_blank():
    K = np.array([[900.0, 0.0, 640.0], [0.0, 900.0, 360.0], [0.0, 0.0, 1.0]])
    dist = np.zeros(5)
    blank = np.full((720, 1280, 3), 200, dtype=np.uint8)
    assert detect_board(blank, K, dist, DEFAULT_BOARD) is None
